-- Safe SQL to DELETE broken streams from public.streams table
-- Review this carefully before executing in Supabase SQL Editor
-- This will delete rows where endpoint matches any of the broken endpoints below

DELETE FROM public.streams
WHERE endpoint IN (
  'wss://mainnet.helius-rpc.com/?api-key=FREE',
  'wss://solana-mainnet.quiknode.pro/free',
  'wss://base-mainnet.g.alchemy.com/v2/demo',
  'wss://testnet.berachain.com/ws',
  'wss://blast-api.publicnode.com',
  'wss://eth-mainnet.alchemyapi.io/v2/demo',
  'wss://arbitrum.gmx.io/ws',
  'wss://arbitrum-mainnet.g.alchemy.com/v2/demo',
  'wss://stream.bybit.com/v5/public/linear',
  'wss://ws.okx.com:8443/ws/v5/public',
  'wss://futures.kraken.com/ws/v1',
  'wss://advanced-trade-ws.coinbase.com',
  'wss://eth-mainnet.g.alchemy.com/v2/demo',
  'wss://api.uniswap.org/v2',
  'wss://quote-api.jup.ag/v6',
  'wss://toncenter.com/api/v2/websocket',
  'wss://fullnode.mainnet.sui.io:443',
  'wss://ordinals.hiro.so/ingest',
  'wss://starknet-mainnet.public.blastapi.io',
  'wss://api.kaspa.org/websocket',
  'wss://api.blxrbdn.com/ws',
  'wss://api.hyperliquid.xyz/ws',
  'wss://fstream.binance.com/ws/!markPrice@arr',
  'wss://hermes.pyth.network/ws',
  'wss://bundles-api-rest.jito.wtf/api/v1/bundles/tip_stream',
  'wss://pumpportal.fun/api/data',
  'wss://polygon-zkevm-mainnet.g.alchemy.com/v2/demo',
  'wss://opt-mainnet.g.alchemy.com/v2/demo',
  'wss://scroll-mainnet.public.blastapi.io',
  'wss://linea-mainnet.g.alchemy.com/v2/demo',
  'wss://zksync-mainnet.g.alchemy.com/v2/demo',
  'wss://mantle-mainnet.public.blastapi.io',
  'wss://api.avax.network/ext/bc/C/ws',
  'wss://ws.fantom.network',
  'wss://node.cronos.org/ws',
  'wss://rpc.gnosischain.com/wss',
  'wss://wss.api.moonbeam.network',
  'wss://forno.celo.org/ws',
  'wss://ws.s0.t.hmny.io',
  'wss://mainnet.aurora.dev',
  'wss://andromeda.metis.io/?owner=0xA&ws',
  'wss://canto.gravitychain.io/ws',
  'wss://evm.kava.io/ws',
  'wss://sapphire.oasis.io/ws',
  'wss://fullnode.mainnet.aptoslabs.com/v1',
  'wss://fullnode.testnet.sui.io:443'
);

-- Optional: Preview what will be deleted (run this first to verify)
-- SELECT id, name, endpoint FROM public.streams
-- WHERE endpoint IN (
--   'wss://mainnet.helius-rpc.com/?api-key=FREE',
--   'wss://solana-mainnet.quiknode.pro/free',
--   'wss://base-mainnet.g.alchemy.com/v2/demo',
--   'wss://testnet.berachain.com/ws',
--   'wss://blast-api.publicnode.com',
--   'wss://eth-mainnet.alchemyapi.io/v2/demo',
--   'wss://arbitrum.gmx.io/ws',
--   'wss://arbitrum-mainnet.g.alchemy.com/v2/demo',
--   'wss://stream.bybit.com/v5/public/linear',
--   'wss://ws.okx.com:8443/ws/v5/public',
--   'wss://futures.kraken.com/ws/v1',
--   'wss://advanced-trade-ws.coinbase.com',
--   'wss://eth-mainnet.g.alchemy.com/v2/demo',
--   'wss://api.uniswap.org/v2',
--   'wss://quote-api.jup.ag/v6',
--   'wss://toncenter.com/api/v2/websocket',
--   'wss://fullnode.mainnet.sui.io:443',
--   'wss://ordinals.hiro.so/ingest',
--   'wss://starknet-mainnet.public.blastapi.io',
--   'wss://api.kaspa.org/websocket',
--   'wss://api.blxrbdn.com/ws',
--   'wss://api.hyperliquid.xyz/ws',
--   'wss://fstream.binance.com/ws/!markPrice@arr',
--   'wss://hermes.pyth.network/ws',
--   'wss://bundles-api-rest.jito.wtf/api/v1/bundles/tip_stream',
--   'wss://pumpportal.fun/api/data',
--   'wss://polygon-zkevm-mainnet.g.alchemy.com/v2/demo',
--   'wss://opt-mainnet.g.alchemy.com/v2/demo',
--   'wss://scroll-mainnet.public.blastapi.io',
--   'wss://linea-mainnet.g.alchemy.com/v2/demo',
--   'wss://zksync-mainnet.g.alchemy.com/v2/demo',
--   'wss://mantle-mainnet.public.blastapi.io',
--   'wss://api.avax.network/ext/bc/C/ws',
--   'wss://ws.fantom.network',
--   'wss://node.cronos.org/ws',
--   'wss://rpc.gnosischain.com/wss',
--   'wss://wss.api.moonbeam.network',
--   'wss://forno.celo.org/ws',
--   'wss://ws.s0.t.hmny.io',
--   'wss://mainnet.aurora.dev',
--   'wss://andromeda.metis.io/?owner=0xA&ws',
--   'wss://canto.gravitychain.io/ws',
--   'wss://evm.kava.io/ws',
--   'wss://sapphire.oasis.io/ws',
--   'wss://fullnode.mainnet.aptoslabs.com/v1',
--   'wss://fullnode.testnet.sui.io:443'
-- );

